Repository fadhilansyah25/Hacktiv8, pull requests merged in 2022-08, with the labels that each got.

#1 Summary HTML dan CSS dasar
  1. HTML & CSS dasar/1. HTML/index.html
  1. HTML & CSS dasar/1. HTML/readme.md
  1. HTML & CSS dasar/2. CSS/readme.md
  1. HTML & CSS dasar/2. CSS/style.css
  1. HTML & CSS dasar/3. Web Design/backgroung-image-gradient.png
  1. HTML & CSS dasar/3. Web Design/blur-image.png
  1. HTML & CSS dasar/3. Web Design/layouting.png
  1. HTML & CSS dasar/3. Web Design/overlay-example.jpg
  1. HTML & CSS dasar/3. Web Design/readme.md
  1. HTML & CSS dasar/3. Web Design/spacing.png
  1. HTML & CSS dasar/3. Web Design/text-on-card.png
  1. HTML & CSS dasar/4. Memaksimalkan Website/author.jpg
  1. HTML & CSS dasar/4. Memaksimalkan Website/images.jpg
  1. HTML & CSS dasar/4. Memaksimalkan Website/index.html
  1. HTML & CSS dasar/4. Memaksimalkan Website/readme.md
  1. HTML & CSS dasar/4. Memaksimalkan Website/styles.css
  1. HTML & CSS dasar/readme.md
Labels: documentation

#2 Fixing formatting on readme.md file
  1. HTML & CSS dasar/1. HTML/readme.md
  1. HTML & CSS dasar/2. CSS/readme.md
  1. HTML & CSS dasar/3. Web Design/readme.md
Labels: documentation, enhancement

#4 Assignment 1 Hacktiv8: Membuat Calculator Sederhana
  4. Assignment 1/hasil-akhir-calculator-sederhana.png
  4. Assignment 1/index.html
  4. Assignment 1/readme.md
  4. Assignment 1/script.js
  4. Assignment 1/style.css
Labels: enhancement

#5 Add documentation and summary session 1 contents Hacktiv8 RCTN class
  2. Sesi 1/intro-to-js.js
  2. Sesi 1/readme.md
Labels: documentation, enhancement

#7 Add documentation and summary from learning materials session 2 Hacktiv8 RCTN class
  3. Sesi 2/contoh-dom.html
  3. Sesi 2/contoh-dom.js
  3. Sesi 2/materi.js
  3. Sesi 2/mentee-task-exercise.js
  3. Sesi 2/mentor-exercise-example.js
  3. Sesi 2/readme.md
Labels: documentation, enhancement

#8 update main README.md layout and description
  README.md
Labels: documentation

#9 Fix all documentation formatting
  2. Sesi 1/readme.md
  3. Sesi 2/readme.md
  4. Assignment 1/readme.md
Labels: documentation, enhancement
